service: export-nudger # NOTE: update this with your service name
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
#plugins:
#  - serverless-local-schedule
functions:
  nudger:
    handler: handler.nudger
    events:
      - schedule:
          name: send-export-feedback-nudge
          description: Sends a message to Slack for people to give feedback
          # every weekday at 9am
          rate: cron(0 7 ? * MON-FRI *)
          #timezone: Europe/Paris
